AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline for Batch Pipeline using GitHub OAuth Version 1'

Parameters:
  GitHubOwner:
    Type: String
    Default: 'kavyarana'
    Description: GitHub Username
  GitHubRepo:
    Type: String
    Default: 'cryptocurrency-data-pipeline'
    Description: GitHub Repository Name
  GitHubBranch:
    Type: String
    Default: 'main'
    Description: Branch to monitor
  GitHubToken:
    Type: String
    NoEcho: true
    Description: 'Personal Access Token (PAT) from GitHub with repo and admin:repo_hook scopes'
  CodePipelineRoleArn:
    Type: String
    Description: ARN of CodePipeline service role
  CodeBuildProjectName:
    Type: String
    Description: Name of CodeBuild project

Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Using AccountId to ensure bucket name uniqueness
      BucketName: !Sub 'crypto-batch-pipeline-artifacts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: crypto-batch-pipeline-cicd
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStoreBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                # This ensures the pipeline checks for changes automatically
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: BuildAndDeploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput

Outputs:
  PipelineName:
    Description: Pipeline Name
    Value: !Ref Pipeline
  
  PipelineUrl:
    Description: Pipeline URL
    Value: !Sub 'https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${Pipeline}/view?region=${AWS::Region}'
  
  ArtifactBucket:
    Description: Artifact Storage Bucket
    Value: !Ref ArtifactStoreBucket
